models:
  - qwen3:8b

methods:
  - rule-based

dataPath: "./datasets/balanced-10x3.json"

llm:
  baseUrl: "http://172.18.144.1:11434"
  apiKey: "ollama"
  temperature: 0.1
  timeout: 30000

schema:
  name: "minimal"