model:
  name: "qwen2.5-coder:7b"
  temperature: 0.1
  baseUrl: "http://172.18.144.1:11434"
  thinkingEnabled: false

mcp:
  servers:
    filesystem:
      transport: stdio
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
    
    # Example: Additional servers can be added here
    # git:
    #   transport: stdio
    #   command: "npx"
    #   args: ["-y", "@modelcontextprotocol/server-git"]

memory:
  enabled: false
  type: "memory"

ui:
  theme: "dark"
  showTimestamps: true
  progressIndicators: true
