app:
  name: "test-app"
  version: "v-0.1.0"
  debug: false

model:
  provider: "ollama"
  name: "qwen2.5-coder:7b"
  temperature: 0.1
  baseUrl: "http://localhost:11434"
  thinkingEnabled: false

ui:
  theme: "dark"
  showTimestamps: true
  progressIndicators: true